version: '2'
services:
    ima-app:
        image: ima
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://ima-mysql:3306/ima?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8040:8040
    ima-mysql:
        extends:
            file: mysql.yml
            service: ima-mysql
